const BASE_IMAGE_URL = "https://image.tmdb.org/t/p/";
const DEFAULT_THUMBNAIL_IMAGE =
  "https://www.themoviedb.org/assets/2/v4/logos/v2/blue_square_1-5bdc75aaebeb75dc7ae79426ddd9be3b2be1e342510f8202baf6bffa71d7f5c4.svg";
const DESKTOP_WIDTH_THRESHOLD = 1024;
const TABLET_WIDTH_THRESHOLD = 768;
const MOBILE_WIDTH_THRESHOLD = 480;
const THUMBNAIL_WIDTH_DESKTOP = "w300";
const THUMBNAIL_WIDTH_MOBILE = "w185";
const HERO_IMG_WIDTH_DESKTOP = "w1280";
const HERO_IMG_WIDTH_TABLET = "w780";
const HERO_IMG_WIDTH_MOBILE = "w500";

export {
  BASE_IMAGE_URL,
  DEFAULT_THUMBNAIL_IMAGE,
  DESKTOP_WIDTH_THRESHOLD,
  TABLET_WIDTH_THRESHOLD,
  MOBILE_WIDTH_THRESHOLD,
  THUMBNAIL_WIDTH_DESKTOP,
  THUMBNAIL_WIDTH_MOBILE,
  HERO_IMG_WIDTH_DESKTOP,
  HERO_IMG_WIDTH_TABLET,
  HERO_IMG_WIDTH_MOBILE,
};
